export type LeetCodeProblemSeed = {
  id: number;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  tags: string[];
  args: string;
  titleSlug: string;
};

export const leetcodeOneToHundredProblems: LeetCodeProblemSeed[] = [
  { id: 1, title: 'Two Sum', difficulty: 'Easy', tags: ['array', 'hash table'], args: '[[2, 7, 11, 15], 9]', titleSlug: 'two-sum' },
  { id: 2, title: 'Add Two Numbers', difficulty: 'Medium', tags: ['linked list', 'math', 'recursion'], args: '[[2, 4, 3], [5, 6, 4]]', titleSlug: 'add-two-numbers' },
  { id: 3, title: 'Longest Substring Without Repeating Characters', difficulty: 'Medium', tags: ['hash table', 'string', 'sliding window'], args: '["abcabcbb"]', titleSlug: 'longest-substring-without-repeating-characters' },
  { id: 4, title: 'Median of Two Sorted Arrays', difficulty: 'Hard', tags: ['array', 'binary search', 'divide and conquer'], args: '[[1, 3], [2]]', titleSlug: 'median-of-two-sorted-arrays' },
  { id: 5, title: 'Longest Palindromic Substring', difficulty: 'Medium', tags: ['string', 'dynamic programming'], args: '["babad"]', titleSlug: 'longest-palindromic-substring' },
  { id: 6, title: 'Zigzag Conversion', difficulty: 'Medium', tags: ['string'], args: '["PAYPALISHIRING", 3]', titleSlug: 'zigzag-conversion' },
  { id: 7, title: 'Reverse Integer', difficulty: 'Medium', tags: ['math'], args: '[123]', titleSlug: 'reverse-integer' },
  { id: 8, title: 'String to Integer (atoi)', difficulty: 'Medium', tags: ['string'], args: '["42"]', titleSlug: 'string-to-integer-atoi' },
  { id: 9, title: 'Palindrome Number', difficulty: 'Easy', tags: ['math'], args: '[121]', titleSlug: 'palindrome-number' },
  { id: 10, title: 'Regular Expression Matching', difficulty: 'Hard', tags: ['string', 'dynamic programming', 'recursion'], args: '["aa", "a*"]', titleSlug: 'regular-expression-matching' },
  { id: 11, title: 'Container With Most Water', difficulty: 'Medium', tags: ['array', 'two pointers', 'greedy'], args: '[[1, 8, 6, 2, 5, 4, 8, 3, 7]]', titleSlug: 'container-with-most-water' },
  { id: 12, title: 'Integer to Roman', difficulty: 'Medium', tags: ['hash table', 'math', 'string'], args: '[3749]', titleSlug: 'integer-to-roman' },
  { id: 13, title: 'Roman to Integer', difficulty: 'Easy', tags: ['hash table', 'math', 'string'], args: '["MCMXCIV"]', titleSlug: 'roman-to-integer' },
  { id: 14, title: 'Longest Common Prefix', difficulty: 'Easy', tags: ['string', 'trie'], args: '[["flower", "flow", "flight"]]', titleSlug: 'longest-common-prefix' },
  { id: 15, title: '3Sum', difficulty: 'Medium', tags: ['array', 'two pointers', 'sorting'], args: '[[-1, 0, 1, 2, -1, -4]]', titleSlug: '3sum' },
  { id: 16, title: '3Sum Closest', difficulty: 'Medium', tags: ['array', 'two pointers', 'sorting'], args: '[[-1, 2, 1, -4], 1]', titleSlug: '3sum-closest' },
  { id: 17, title: 'Letter Combinations of a Phone Number', difficulty: 'Medium', tags: ['hash table', 'string', 'backtracking'], args: '["23"]', titleSlug: 'letter-combinations-of-a-phone-number' },
  { id: 18, title: '4Sum', difficulty: 'Medium', tags: ['array', 'two pointers', 'sorting'], args: '[[1, 0, -1, 0, -2, 2], 0]', titleSlug: '4sum' },
  { id: 19, title: 'Remove Nth Node From End of List', difficulty: 'Medium', tags: ['linked list', 'two pointers'], args: '[[1, 2, 3, 4, 5], 2]', titleSlug: 'remove-nth-node-from-end-of-list' },
  { id: 20, title: 'Valid Parentheses', difficulty: 'Easy', tags: ['string', 'stack'], args: '["()[]{}"]', titleSlug: 'valid-parentheses' },
  { id: 21, title: 'Merge Two Sorted Lists', difficulty: 'Easy', tags: ['linked list', 'recursion'], args: '[[1, 2, 4], [1, 3, 4]]', titleSlug: 'merge-two-sorted-lists' },
  { id: 22, title: 'Generate Parentheses', difficulty: 'Medium', tags: ['string', 'dynamic programming', 'backtracking'], args: '[3]', titleSlug: 'generate-parentheses' },
  { id: 23, title: 'Merge k Sorted Lists', difficulty: 'Hard', tags: ['linked list', 'divide and conquer', 'heap'], args: '[[[1, 4, 5], [1, 3, 4], [2, 6]]]', titleSlug: 'merge-k-sorted-lists' },
  { id: 24, title: 'Swap Nodes in Pairs', difficulty: 'Medium', tags: ['linked list', 'recursion'], args: '[[1, 2, 3, 4]]', titleSlug: 'swap-nodes-in-pairs' },
  { id: 25, title: 'Reverse Nodes in k-Group', difficulty: 'Hard', tags: ['linked list', 'recursion'], args: '[[1, 2, 3, 4, 5], 2]', titleSlug: 'reverse-nodes-in-k-group' },
  { id: 26, title: 'Remove Duplicates from Sorted Array', difficulty: 'Easy', tags: ['array', 'two pointers'], args: '[[1, 1, 2]]', titleSlug: 'remove-duplicates-from-sorted-array' },
  { id: 27, title: 'Remove Element', difficulty: 'Easy', tags: ['array', 'two pointers'], args: '[[3, 2, 2, 3], 3]', titleSlug: 'remove-element' },
  { id: 28, title: 'Find the Index of the First Occurrence in a String', difficulty: 'Easy', tags: ['two pointers', 'string', 'string matching'], args: '["sadbutsad", "sad"]', titleSlug: 'find-the-index-of-the-first-occurrence-in-a-string' },
  { id: 29, title: 'Divide Two Integers', difficulty: 'Medium', tags: ['math', 'bit manipulation'], args: '[10, 3]', titleSlug: 'divide-two-integers' },
  { id: 30, title: 'Substring with Concatenation of All Words', difficulty: 'Hard', tags: ['hash table', 'string', 'sliding window'], args: '["barfoothefoobarman", ["foo", "bar"]]', titleSlug: 'substring-with-concatenation-of-all-words' },
  { id: 31, title: 'Next Permutation', difficulty: 'Medium', tags: ['array', 'two pointers'], args: '[[1, 2, 3]]', titleSlug: 'next-permutation' },
  { id: 32, title: 'Longest Valid Parentheses', difficulty: 'Hard', tags: ['string', 'dynamic programming', 'stack'], args: '["(()"]', titleSlug: 'longest-valid-parentheses' },
  { id: 33, title: 'Search in Rotated Sorted Array', difficulty: 'Medium', tags: ['array', 'binary search'], args: '[[4, 5, 6, 7, 0, 1, 2], 0]', titleSlug: 'search-in-rotated-sorted-array' },
  { id: 34, title: 'Find First and Last Position of Element in Sorted Array', difficulty: 'Medium', tags: ['array', 'binary search'], args: '[[5, 7, 7, 8, 8, 10], 8]', titleSlug: 'find-first-and-last-position-of-element-in-sorted-array' },
  { id: 35, title: 'Search Insert Position', difficulty: 'Easy', tags: ['array', 'binary search'], args: '[[1, 3, 5, 6], 5]', titleSlug: 'search-insert-position' },
  { id: 36, title: 'Valid Sudoku', difficulty: 'Medium', tags: ['array', 'hash table', 'matrix'], args: '[[["5","3",".",".","7",".",".",".","."],["6",".",".","1","9","5",".",".","."],[".","9","8",".",".",".",".","6","."],["8",".",".",".","6",".",".",".","3"],["4",".",".","8",".","3",".",".","1"],["7",".",".",".","2",".",".",".","6"],[".","6",".",".",".",".","2","8","."],[".",".",".","4","1","9",".",".","5"],[".",".",".",".","8",".",".","7","9"]]]', titleSlug: 'valid-sudoku' },
  { id: 37, title: 'Sudoku Solver', difficulty: 'Hard', tags: ['array', 'backtracking', 'matrix'], args: '[[["5","3",".",".","7",".",".",".","."],["6",".",".","1","9","5",".",".","."],[".","9","8",".",".",".",".","6","."],["8",".",".",".","6",".",".",".","3"],["4",".",".","8",".","3",".",".","1"],["7",".",".",".","2",".",".",".","6"],[".","6",".",".",".",".","2","8","."],[".",".",".","4","1","9",".",".","5"],[".",".",".",".","8",".",".","7","9"]]]', titleSlug: 'sudoku-solver' },
  { id: 38, title: 'Count and Say', difficulty: 'Medium', tags: ['string'], args: '[4]', titleSlug: 'count-and-say' },
  { id: 39, title: 'Combination Sum', difficulty: 'Medium', tags: ['array', 'backtracking'], args: '[[2, 3, 6, 7], 7]', titleSlug: 'combination-sum' },
  { id: 40, title: 'Combination Sum II', difficulty: 'Medium', tags: ['array', 'backtracking'], args: '[[10, 1, 2, 7, 6, 1, 5], 8]', titleSlug: 'combination-sum-ii' },
  { id: 41, title: 'First Missing Positive', difficulty: 'Hard', tags: ['array', 'hash table'], args: '[[1, 2, 0]]', titleSlug: 'first-missing-positive' },
  { id: 42, title: 'Trapping Rain Water', difficulty: 'Hard', tags: ['array', 'two pointers', 'dynamic programming', 'stack'], args: '[[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]]', titleSlug: 'trapping-rain-water' },
  { id: 43, title: 'Multiply Strings', difficulty: 'Medium', tags: ['math', 'string', 'simulation'], args: '["123", "456"]', titleSlug: 'multiply-strings' },
  { id: 44, title: 'Wildcard Matching', difficulty: 'Hard', tags: ['string', 'dynamic programming', 'greedy'], args: '["aa", "*"]', titleSlug: 'wildcard-matching' },
  { id: 45, title: 'Jump Game II', difficulty: 'Medium', tags: ['array', 'dynamic programming', 'greedy'], args: '[[2, 3, 1, 1, 4]]', titleSlug: 'jump-game-ii' },
  { id: 46, title: 'Permutations', difficulty: 'Medium', tags: ['array', 'backtracking'], args: '[[1, 2, 3]]', titleSlug: 'permutations' },
  { id: 47, title: 'Permutations II', difficulty: 'Medium', tags: ['array', 'backtracking'], args: '[[1, 1, 2]]', titleSlug: 'permutations-ii' },
  { id: 48, title: 'Rotate Image', difficulty: 'Medium', tags: ['array', 'math', 'matrix'], args: '[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]', titleSlug: 'rotate-image' },
  { id: 49, title: 'Group Anagrams', difficulty: 'Medium', tags: ['array', 'hash table', 'string', 'sorting'], args: '[["eat", "tea", "tan", "ate", "nat", "bat"]]', titleSlug: 'group-anagrams' },
  { id: 50, title: 'Pow(x, n)', difficulty: 'Medium', tags: ['math', 'recursion'], args: '[2.0, 10]', titleSlug: 'powx-n' },
  { id: 51, title: 'N-Queens', difficulty: 'Hard', tags: ['array', 'backtracking'], args: '[4]', titleSlug: 'n-queens' },
  { id: 52, title: 'N-Queens II', difficulty: 'Hard', tags: ['backtracking'], args: '[4]', titleSlug: 'n-queens-ii' },
  { id: 53, title: 'Maximum Subarray', difficulty: 'Medium', tags: ['array', 'dynamic programming'], args: '[[-2, 1, -3, 4, -1, 2, 1, -5, 4]]', titleSlug: 'maximum-subarray' },
  { id: 54, title: 'Spiral Matrix', difficulty: 'Medium', tags: ['array', 'matrix', 'simulation'], args: '[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]', titleSlug: 'spiral-matrix' },
  { id: 55, title: 'Jump Game', difficulty: 'Medium', tags: ['array', 'dynamic programming', 'greedy'], args: '[[2, 3, 1, 1, 4]]', titleSlug: 'jump-game' },
  { id: 56, title: 'Merge Intervals', difficulty: 'Medium', tags: ['array', 'sorting'], args: '[[[1, 3], [2, 6], [8, 10], [15, 18]]]', titleSlug: 'merge-intervals' },
  { id: 57, title: 'Insert Interval', difficulty: 'Medium', tags: ['array'], args: '[[[1, 3], [6, 9]], [2, 5]]', titleSlug: 'insert-interval' },
  { id: 58, title: 'Length of Last Word', difficulty: 'Easy', tags: ['string'], args: '["Hello World"]', titleSlug: 'length-of-last-word' },
  { id: 59, title: 'Spiral Matrix II', difficulty: 'Medium', tags: ['array', 'matrix', 'simulation'], args: '[3]', titleSlug: 'spiral-matrix-ii' },
  { id: 60, title: 'Permutation Sequence', difficulty: 'Hard', tags: ['math', 'recursion'], args: '[3, 3]', titleSlug: 'permutation-sequence' },
  { id: 61, title: 'Rotate List', difficulty: 'Medium', tags: ['linked list', 'two pointers'], args: '[[1, 2, 3, 4, 5], 2]', titleSlug: 'rotate-list' },
  { id: 62, title: 'Unique Paths', difficulty: 'Medium', tags: ['math', 'dynamic programming', 'combinatorics'], args: '[3, 7]', titleSlug: 'unique-paths' },
  { id: 63, title: 'Unique Paths II', difficulty: 'Medium', tags: ['array', 'dynamic programming', 'matrix'], args: '[[[0, 0, 0], [0, 1, 0], [0, 0, 0]]]', titleSlug: 'unique-paths-ii' },
  { id: 64, title: 'Minimum Path Sum', difficulty: 'Medium', tags: ['array', 'dynamic programming', 'matrix'], args: '[[[1, 3, 1], [1, 5, 1], [4, 2, 1]]]', titleSlug: 'minimum-path-sum' },
  { id: 65, title: 'Valid Number', difficulty: 'Hard', tags: ['string'], args: '["0"]', titleSlug: 'valid-number' },
  { id: 66, title: 'Plus One', difficulty: 'Easy', tags: ['array', 'math'], args: '[[1, 2, 3]]', titleSlug: 'plus-one' },
  { id: 67, title: 'Add Binary', difficulty: 'Easy', tags: ['math', 'string', 'bit manipulation'], args: '["11", "1"]', titleSlug: 'add-binary' },
  { id: 68, title: 'Text Justification', difficulty: 'Hard', tags: ['array', 'string', 'simulation'], args: '[["This", "is", "an", "example", "of", "text", "justification."], 16]', titleSlug: 'text-justification' },
  { id: 69, title: 'Sqrt(x)', difficulty: 'Easy', tags: ['math', 'binary search'], args: '[8]', titleSlug: 'sqrtx' },
  { id: 70, title: 'Climbing Stairs', difficulty: 'Easy', tags: ['math', 'dynamic programming'], args: '[3]', titleSlug: 'climbing-stairs' },
  { id: 71, title: 'Simplify Path', difficulty: 'Medium', tags: ['string', 'stack'], args: '["/home//foo/"]', titleSlug: 'simplify-path' },
  { id: 72, title: 'Edit Distance', difficulty: 'Medium', tags: ['string', 'dynamic programming'], args: '["horse", "ros"]', titleSlug: 'edit-distance' },
  { id: 73, title: 'Set Matrix Zeroes', difficulty: 'Medium', tags: ['array', 'hash table', 'matrix'], args: '[[[1, 1, 1], [1, 0, 1], [1, 1, 1]]]', titleSlug: 'set-matrix-zeroes' },
  { id: 74, title: 'Search a 2D Matrix', difficulty: 'Medium', tags: ['array', 'binary search', 'matrix'], args: '[[[1, 3, 5, 7], [10, 11, 16, 20], [23, 30, 34, 60]], 3]', titleSlug: 'search-a-2d-matrix' },
  { id: 75, title: 'Sort Colors', difficulty: 'Medium', tags: ['array', 'two pointers', 'sorting'], args: '[[2, 0, 2, 1, 1, 0]]', titleSlug: 'sort-colors' },
  { id: 76, title: 'Minimum Window Substring', difficulty: 'Hard', tags: ['hash table', 'string', 'sliding window'], args: '["ADOBECODEBANC", "ABC"]', titleSlug: 'minimum-window-substring' },
  { id: 77, title: 'Combinations', difficulty: 'Medium', tags: ['backtracking'], args: '[4, 2]', titleSlug: 'combinations' },
  { id: 78, title: 'Subsets', difficulty: 'Medium', tags: ['array', 'backtracking', 'bit manipulation'], args: '[[1, 2, 3]]', titleSlug: 'subsets' },
  { id: 79, title: 'Word Search', difficulty: 'Medium', tags: ['array', 'string', 'backtracking', 'matrix'], args: '[[["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], "ABCCED"]', titleSlug: 'word-search' },
  { id: 80, title: 'Remove Duplicates from Sorted Array II', difficulty: 'Medium', tags: ['array', 'two pointers'], args: '[[1, 1, 1, 2, 2, 3]]', titleSlug: 'remove-duplicates-from-sorted-array-ii' },
  { id: 81, title: 'Search in Rotated Sorted Array II', difficulty: 'Medium', tags: ['array', 'binary search'], args: '[[2, 5, 6, 0, 0, 1, 2], 0]', titleSlug: 'search-in-rotated-sorted-array-ii' },
  { id: 82, title: 'Remove Duplicates from Sorted List II', difficulty: 'Medium', tags: ['linked list', 'two pointers'], args: '[[1, 2, 3, 3, 4, 4, 5]]', titleSlug: 'remove-duplicates-from-sorted-list-ii' },
  { id: 83, title: 'Remove Duplicates from Sorted List', difficulty: 'Easy', tags: ['linked list'], args: '[[1, 1, 2]]', titleSlug: 'remove-duplicates-from-sorted-list' },
  { id: 84, title: 'Largest Rectangle in Histogram', difficulty: 'Hard', tags: ['array', 'stack', 'monotonic stack'], args: '[[2, 1, 5, 6, 2, 3]]', titleSlug: 'largest-rectangle-in-histogram' },
  { id: 85, title: 'Maximal Rectangle', difficulty: 'Hard', tags: ['array', 'dynamic programming', 'stack', 'matrix'], args: '[[["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]]]', titleSlug: 'maximal-rectangle' },
  { id: 86, title: 'Partition List', difficulty: 'Medium', tags: ['linked list', 'two pointers'], args: '[[1, 4, 3, 2, 5, 2], 3]', titleSlug: 'partition-list' },
  { id: 87, title: 'Scramble String', difficulty: 'Hard', tags: ['string', 'dynamic programming'], args: '["great", "rgeat"]', titleSlug: 'scramble-string' },
  { id: 88, title: 'Merge Sorted Array', difficulty: 'Easy', tags: ['array', 'two pointers', 'sorting'], args: '[[1, 2, 3, 0, 0, 0], 3, [2, 5, 6], 3]', titleSlug: 'merge-sorted-array' },
  { id: 89, title: 'Gray Code', difficulty: 'Medium', tags: ['math', 'backtracking', 'bit manipulation'], args: '[2]', titleSlug: 'gray-code' },
  { id: 90, title: 'Subsets II', difficulty: 'Medium', tags: ['array', 'backtracking', 'bit manipulation'], args: '[[1, 2, 2]]', titleSlug: 'subsets-ii' },
  { id: 91, title: 'Decode Ways', difficulty: 'Medium', tags: ['string', 'dynamic programming'], args: '["12"]', titleSlug: 'decode-ways' },
  { id: 92, title: 'Reverse Linked List II', difficulty: 'Medium', tags: ['linked list'], args: '[[1, 2, 3, 4, 5], 2, 4]', titleSlug: 'reverse-linked-list-ii' },
  { id: 93, title: 'Restore IP Addresses', difficulty: 'Medium', tags: ['string', 'backtracking'], args: '["25525511135"]', titleSlug: 'restore-ip-addresses' },
  { id: 94, title: 'Binary Tree Inorder Traversal', difficulty: 'Easy', tags: ['stack', 'tree', 'depth-first search', 'binary tree'], args: '[[1, null, 2, 3]]', titleSlug: 'binary-tree-inorder-traversal' },
  { id: 95, title: 'Unique Binary Search Trees II', difficulty: 'Medium', tags: ['dynamic programming', 'backtracking', 'tree', 'binary search tree'], args: '[3]', titleSlug: 'unique-binary-search-trees-ii' },
  { id: 96, title: 'Unique Binary Search Trees', difficulty: 'Medium', tags: ['math', 'dynamic programming', 'tree', 'binary search tree'], args: '[3]', titleSlug: 'unique-binary-search-trees' },
  { id: 97, title: 'Interleaving String', difficulty: 'Medium', tags: ['string', 'dynamic programming'], args: '["aabcc", "dbbca", "aadbbcbcac"]', titleSlug: 'interleaving-string' },
  { id: 98, title: 'Validate Binary Search Tree', difficulty: 'Medium', tags: ['tree', 'depth-first search', 'binary search tree', 'binary tree'], args: '[[2, 1, 3]]', titleSlug: 'validate-binary-search-tree' },
  { id: 99, title: 'Recover Binary Search Tree', difficulty: 'Medium', tags: ['tree', 'depth-first search', 'binary search tree', 'binary tree'], args: '[[1, 3, null, null, 2]]', titleSlug: 'recover-binary-search-tree' },
  { id: 100, title: 'Same Tree', difficulty: 'Easy', tags: ['tree', 'depth-first search', 'breadth-first search', 'binary tree'], args: '[[1, 2, 3], [1, 2, 3]]', titleSlug: 'same-tree' },
];
